version: '3.7'

services:
  database:
    build:
      context: mysql
    container_name: database
    restart: always

    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: fullcycle
    volumes:
      - ./mysql/volume:/var/lib/mysql
    networks:
      - nodenet

  app:
    build:
      context: app
    container_name: app
    entrypoint: dockerize -wait tcp://database:3306 -timeout 10s docker-entrypoint.sh
    tty: true
    restart: always
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - database
    networks:
      - nodenet
    command: npm run start

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    networks:
      - nodenet
    depends_on:
      - app

networks:
  nodenet:
    driver: bridge
